advogaprojeto/advogaprojeto/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('core.urls'))
]

advogaprojeto/core/urls.py
from django.conf.urls import url
from core import views
from django.contrib import admin

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^registrar/$', views.registrar, name='registrar'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.log_out, name='logout'),
    url(r'^index/$', views.index, name='index'),
    url(r'^gerar_documento$', views.gerar_documento, name='gerar_documento'),
    url(r'^cadastro$', views.cadastrar_documento, name='cadastrar_documento'),
    url(r'^documento/(?P<id_arquivo>\d+)$', views.documento, name='documento'),
    url(r'^delete/(?P<id_template>\d+)$', views.delete_template, name='delete')
]

advogaprojeto/core/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Usuario(models.Model):

    nome = models.CharField(max_length=50, null=False, unique=True)
    telefone = models.CharField(max_length=12, null=False)
    email = models.CharField(max_length=30, null=False, unique=True)
    user = models.OneToOneField(User, related_name="Usuario")


class TemplateFile(models.Model):

    nome = models.CharField(max_length=30, null=False, unique=True)
    descricao = models.TextField(max_length=100, null=False)
    data = models.DateField(auto_now_add=True)
    arquivo = models.FileField(upload_to='product/%Y/%m/%d')
    user = models.ForeignKey(Usuario, on_delete=models.CASCADE)

advogaprojeto/core/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import ModelForm

from core.models import TemplateFile


class RegistrarUsuarioForm(forms.Form):
    nome = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    senha = forms.CharField(required=True)
    telefone = forms.CharField(required=True)

    def is_valid(self):
        valid = True
        if not super(RegistrarUsuarioForm, self).is_valid():
            self.adiciona_erro("Por Favor, verifique os dados informados")
            valid = False
        return valid

    def adiciona_erro(self, message):
        errors = self._errors.setdefault(
            forms.forms.NON_FIELD_ERRORS, forms.utils.ErrorList())
        errors.append(message)


class LogarForm(forms.Form):
    nome = forms.CharField(required=True)
    senha = forms.CharField(required=True)


class TemplateForm(ModelForm):

    class Meta:
        model = TemplateFile
        fields = ['nome', 'descricao', 'arquivo']

advogaprojeto/core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import User
from django.contrib.auth import authenticate, logout
from django.contrib.auth import login as login_page  # edit for name def login
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse

from django.template import RequestContext

from core.forms import RegistrarUsuarioForm, LogarForm, TemplateForm
from core.models import Usuario, TemplateFile
from core.scripts import is_template, clear_query

# Create your views here.


@login_required
def get_user_logado(request):
    usuario = Usuario.objects.get(id=request.user.id)
    return usuario


def home(request):
    if request.user.is_authenticated == True:
        return redirect('index')
    else:
        return render(request, 'home.html')


@login_required
def index(request):
    usuarios = Usuario.objects.all()
    arquivos = TemplateFile.objects.all()
    return render(
        request, 'index.html', {
            "usuario": get_user_logado(request),
            "usuarios": usuarios,
            "arquivos": arquivos}
    )


def login(request):
    if request.method == 'POST':
        form = LogarForm(request.POST)
        dados_form = form.data
        user = authenticate(
            username=dados_form['username'].lower(),
            password=dados_form['password']
        )
        if user is not None:
            login_page(request, user)
            return redirect('index')
    return render(request, 'login.html')


def log_out(request):
    logout(request)
    return redirect('home')


def registrar(request):

    if request.method == 'POST':
        form = RegistrarUsuarioForm(request.POST)
        if form.is_valid():
            dados_form = form.data
            # todo o processo de salvar no bd e criar user
            # criar user
            criar_user = User.objects.create_user(
                dados_form['nome'].lower(),
                dados_form['email'].lower(),
                dados_form['senha']
            )
            # criar Usuario
            usuario = Usuario(
                nome=dados_form['nome'].lower(),
                email=dados_form['email'].lower(),
                telefone=dados_form['telefone'],
                user=criar_user
            )
            # salvar
            usuario.save()
            return redirect('login')
        else:
            return render(request, 'registrar.html', {"form": form})

    return render(request, 'registrar.html')


@login_required
def gerar_documento(request):
    return render(request, 'gerar_documento.html', {"usuario": get_user_logado(request)})


@login_required
def cadastrar_documento(request):
    if request.method == 'POST':
        form = TemplateForm(request.POST, request.FILES)
        if form.is_valid():
            arq = TemplateFile(
                nome=form.data['nome'],
                descricao=form.data['descricao'],
                arquivo=request.FILES['arquivo'],
                user=Usuario.objects.get(id=request.user.id)
            )
            arq.save()
            return redirect('index')
        else:
            return render(request, 'cadastrar_documento.html', {"form": form})
    else:
        arquivos = TemplateFile.objects.all().filter(user=get_user_logado(request))
        return render(request, 'cadastrar_documento.html', {
            "usuario": get_user_logado(request),
            "arquivos_do_user": arquivos}
        )


@login_required
def documento(request, id_arquivo):
    doc = TemplateFile.objects.get(id=id_arquivo)
    try:
        keys = is_template(doc.arquivo.name)
    except:
        raise ("error")

    if not keys:
        return render(request, 'gerar_documento.html', {
            "usuario": get_user_logado(request),
            "arquivo": doc}
        )
    else:
        if request.method == 'POST':
            form = request.POST
            dict_form = form.dict()
            dict_form = clear_query(dict_form)
            response = HttpResponse(content_type='application/vnd.ms-word')
            response[
                'Content-Disposition'] = 'attachment; filename="documento.docx"'
            return response
        return render(request, 'gerar_documento.html', {
            "usuario": get_user_logado(request),
            "arquivo": doc,
            "keys": keys}
        )


@login_required
def delete_template(request, id_template):
    obj = TemplateFile.objects.get(id=id_template)
    obj.delete()
    return redirect('index')

advogaprojeto/core/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static "css/bootstrap.css"%}" rel="stylesheet">
    {% if usuario %}
    <title>Dashboard</title>
    {%else%}
    <title>Bem Vindo</title>
    {%endif%}
    <meta charset="utf-8">
</head>

<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          </button>
                {% if usuario %}
                <a href="{% url 'index' %}" class="navbar-brand">Dashbord</a>
                {% else %}
                <a class="navbar-brand">Bem Vindo!</a>
                {% endif %}
            </div>
        </div>
    </nav>
    <div class="container">
        {%block body%} {%endblock%}
    </div>
</body>

</html>

advogaprojeto/core/templates/base_index.html
{% extends 'base.html' %} {% block body %}
<div class="col-lg-9">
    {% block body_index%} {% endblock %}
</div>
<div class="col-lg-3">
    <!-- menu centro -->
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">Bem vindo <strong>{{usuario.nome|title}}</strong>
                </h3>
        </div>
        <div class="panel-body">
            <table class="table table-striped table-hover ">
                <tbody>
                    <tr>
                        <th>
                            <span class="glyphicon glyphicon-home" aria-hidden="true"></span>
                            <a href="{% url 'index' %}">Home</a>
                        </th>
                    </tr>
                    <!-- <tr>
                        <th>
                            <span class="glyphicon glyphicon-open-file" aria-hidden="true"></span>
                            <a href="{% url 'gerar_documento' %}">Gerar relatório</a>
                        </th>
                    </tr> -->

                    <tr>
                        <th>
                            <span class="glyphicon glyphicon-tasks" aria-hidden="true"></span>
                            <a href="{% url 'cadastrar_documento' %}">Cadastrar documento</a>
                        </th>
                    </tr>

                    <tr>
                        <th>
                            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                            <a href="#">Editar Perfil</a>
                        </th>
                    </tr>
                    <tr class="danger">
                        <th>
                            <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>
                            <a href="{% url 'logout' %}">Logout</a>
                        </th>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>

    {% block menu %} {% endblock %}
</div>
{% endblock %}

advogaprojeto/core/templates/cadastrar_documento.html
{% extends 'base_index.html' %} {% block body_index %}
<div class="col-lg-7">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">Criar um novo Template</h3>
        </div>
        <div class="panel-body">
            <form class="form-horizontal col-lg-12" accept-charset="UTF-8" enctype="multipart/form-data" action="{% url 'cadastrar_documento' %}" method="POST">
                {% csrf_token %}
                <!--  -->
                <div class="form-group">
                    <label for="id_nome" class="control-label">Nome do Template*</label>
                    <div>
                        <input type="text" id="id_nome" name="nome" class="form-control" placeholder="Nome" required autofocus>
                    </div>
                </div>
                <!--  -->
                <div class="form-group">
                    <label for="textArea" class="control-label">Descrição*</label>
                    <div>
                        <textarea placeholder="Descrição" style="width: 100%; height: 163px;" name="descricao" class="form-control" rows="3" id="textArea" class="input" required></textarea>
                        <!-- cols rows for textarea -->
                        <span class="help-block">Um breve descrição sobre o arquivo</span>
                    </div>
                </div>
                <!--  -->
                <div class="form-group">
                    <label for="id_arquivo" class="control-label">Arquivo*</label>
                    <div>
                        <input type="file" accept=".docx" id="id_arquivo" name="arquivo" class="input" placeholder="Upload" required>
                    </div>
                </div>
                <!--  -->
                <div class="form-group">
                    <button class="btn btn-lg btn-primary" type="submit" value="Criar">Salvar Documento</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- outro panel -->
<div class="col-lg-5">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">Seus Templates</h3>
        </div>
        {% if arquivos_do_user %} {% for arquivo in arquivos_do_user%}
        <ul class="list-group">
            <li class="list-group-item">
                {{arquivo.nome}}
            </li>
        </ul>
        {% endfor %} {%else%}
        <ul class="list-group">
            <li class="list-group-item">
                Desculpe, você não templates.
            </li>
        </ul>
        {% endif %}
    </div>
</div>

{{form}} {% endblock %}

advogaprojeto/core/templates/gerar_documento.html
{% extends 'base_index.html' %}
{% block body_index %}
    {% if keys %}
        {# {{key|title}}#}
        <form class="form-horizontal col-lg-12" accept-charset="UTF-8" action="#" method="POST">
            {% csrf_token %}
            {% for key in keys%}
            <div class="form-group">
                <input type="text" id="id_{{key|lower}}" name="{{key}}" class="form-control" placeholder="{{key|title}}" required autofocus>
            </div>
            {%endfor%}
            <div class="form-group">
                <button class="btn btn-lg btn-primary" type="submit" value="Criar">gerar documento</button>
            </div>
        </form>
    {%else%}
    <p>Documento não tem chaves</p>
    {%endif%}
    <a href="{% url 'delete' arquivo.id %}" class="btn">Deletar</a>
{% endblock %}

advogaprojeto/core/templates/home.html
{% extends 'base.html'%} {% block body%}
<div class="col-lg-6 col-lg-offset-3">

    <h1>Bem vindo, loge-se ou registre-se</h1>
    <a href="{% url 'login'%}" class="btn btn-lg btn-primary">Logar</a>
    <a href="{% url 'registrar' %}" class=" btn btn-lg btn-success">Registrar</a>

</div>
{% endblock%}

advogaprojeto/core/templates/index.html
{% extends 'base_index.html' %} {% block body_index %}
<!-- menu lateral -->
<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">Templates criados</h3>
    </div>
    <div class="panel-body">
        {% if arquivos%}
        <table class="table table-striped table-hover ">
            <thead>
                <tr>
                    <th>Nome</th>
                    <th>Descrição</th>
                    <th>Data</th>
                </tr>
            </thead>
            {% for arquivo in arquivos %}
            <tbody>
                <tr>
                    <td><a href="{% url 'documento' arquivo.id%}">{{arquivo.nome}}</a></td>
                    <td>{{arquivo.descricao|truncatechars:12}}</td>
                    <td>{{arquivo.data}}</td>
                </tr>
            </tbody>
            {% endfor %}
        </table>
        {%else%}
        <ul class="list-group">
            <li class="list-group-item">
                Desculpe, você não templates.
            </li>
        </ul>
        {% endif %}
    </div>
</div>

<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">Seus relatrios emitidos</h3>
    </div>
    <div class="panel-body">
    </div>
</div>
{%endblock%}
<!--  -->
{%block menu%}
<div class="panel panel-success">
    <div class="panel-heading">
        <h3 class="panel-title">Todos os usuarios</h3>
    </div>
    <div class="panel-body">
        <table class="table table-striped table-hover ">
            <tbody>
                {% for user in usuarios %} {% if not user.nome == usuario.nome%}
                <tr>
                    <th>
                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span> {{ user.nome|title }}
                    </th>
                </tr>
                {% endif %} {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

advogaprojeto/core/templates/login.html
{%extends "base.html"%} {%block body%}
<div id="loginbox" class="center">
    <form class="col-lg-6 col-lg-offset-3 form-horizontal jumbotron" accept-charset="UTF-8" action="{% url 'login' %}" method="POST">
        {% csrf_token %}
        <legend>Logar</legend>
        <div class="form-group">
            <label for="in_username" class="col-lg-2 control-label">Usuario</label>
            <div class="col-lg-10">
                <input type="text" id="id_username" name="username" class="form-control" placeholder="Usuário" required autofocus>
            </div>
        </div>
        <div class="form-group">
            <label for="in_password" class="col-lg-2 control-label">Senha</label>
            <div class="col-lg-10">
                <input type="password" id="id_password" name="password" class="form-control" placeholder="Senha" required>
            </div>
        </div>

        <div class="col-lg-6">
            <button class="btn btn-success btn-lg btn-block" type="submit" value="Login">Logar</button>
        </div>
        <div class="col-lg-6">
            <a class="btn btn-primary btn-lg btn-block" href="{% url 'registrar'%}">Registrar</a>
        </div>
    </form>
</div>
{%endblock%}

advogaprojeto/core/templates/registrar.html
{% extends "base.html" %} {% block body %}
<div class="center-block">
    <!-- ERROR -->
    {%if form%}
    <div class="alert alert-dismissible alert-danger col-lg-6 col-lg-offset-3">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>{{form.non_field_errors}}</strong>
    </div>
    {%endif%}
    <!---->
    <form id="registrar-form" class="col-lg-6 col-lg-offset-3 form-horizontal jumbotron" accept-charset="UTF-8" action="{% url 'registrar' %}" method="post">
        {% csrf_token %}
        <fieldset>
            <legend>Registrar-se</legend>
            <div class="form-group">
                <label for="in_nome" class="col-lg-2 control-label">Usuario</label>
                <div class="col-lg-10">
                    <input type="text" id="id_nome" name="nome" class="form-control" placeholder="Login" required autofocus>
                </div>
            </div>
            <div class="form-group">
                <label for="in_email" class="col-lg-2 control-label">E-Mail</label>
                <div class="col-lg-10">
                    <input type="email" id="id_email" name="email" class="form-control" placeholder="E-Mail" required>
                </div>
            </div>
            <div class="form-group">
                <label for="in_senha" class="col-lg-2 control-label">Senha</label>
                <div class="col-lg-10">
                    <input type="password" id="id_senha" name="senha" class="form-control" placeholder="Senha" required>
                </div>
            </div>
            <div class="form-group">
                <label for="in_telefone" class="col-lg-2 control-label">Telefone</label>
                <div class="col-lg-10">
                    <input type="tel" id="id_telefone" name="telefone" class="form-control" placeholder="Telefone" required=>
                </div>
            </div>
            <div class="col-lg-6">
                <button class="btn btn-lg btn-primary btn-block btn-success" type="submit" value="Login">Criar</button>
            </div>
            <div class="col-lg-6">
                <button type="reset" class="btn btn-default btn-lg btn-block">Limpar</button>
            </div>

        </fieldset>
    </form>
</div>
{% endblock %}